export const labelMap = {
  name: 'Име',
  fullname: 'Пълно име',
  gender: 'Пол',
  age: 'Възраст',
  height: 'Ръст (см)',
  weight: 'Тегло (кг)',
  email: 'Имейл',
  phone: 'Телефон',
  goal: 'Основна цел',
  mainGoal: 'Основна цел',
  motivation: 'Мотивация',
  motivationLevel: 'Ниво на мотивация',
  weightChange: 'Рязко покачване на тегло',
  dietHistory: 'Диета през последната година',
  sleepHours: 'Продължителност на съня',
  sleepInterrupt: 'Прекъсвания на съня',
  sleepInterruptions: 'Прекъсвания на съня',
  chronotype: 'Хронотип',
  q1745878295708: 'Ниво на активност',
  activityLevel: 'Ниво на активност',
  physicalActivity: 'Физическа активност',
  stressLevel: 'Ниво на стрес',
  waterIntake: 'Прием на вода',
  waterReplaceFreq: 'Замяна на водата с други напитки',
  overeatingFrequency: 'Честота на преяждане',
  foodCravings: 'Желание за определени храни',
  foodTriggers: 'Хранителни тригери',
  nighteat: 'Нощно хранене',
  compensationmethod: 'Метод за компенсация',
  comparisson: 'Сравнение с други',
  q1745805447648: 'Честота на хранене навън',
  q1745805721482: 'Тип хранене навън',
  alcoholFrequency: 'Консумация на алкохол',
  medications: 'Лекарства/добавки',
  medicalConditions: 'Медицински състояния',
  foodPreference: 'Хранителни предпочитания',
  foodPreferences: 'Хранителни предпочитания',
  mainChallenge: 'Основно предизвикателство',
  q1745892518511: 'Допълнителна информация',
  targetBmi: 'Целеви BMI',
  eatingHabits: 'Хранителни навици'
};

