name = "openapichatbot"
account_id = "c2015f4060e04bc3c414f78a9946668e"
workers_dev = true
compatibility_date = "2025-06-20"
compatibility_flags = ["nodejs_compat"]
main = "worker.js"

[[rules]]
globs = ["utils/**/*.js"]
type = "ESModule"

[[kv_namespaces]]
binding = "RESOURCES_KV"
id = "8ebf65a6ed0a44e7b7d1b4bc6f24465e"
preview_id = "8ebf65a6ed0a44e7b7d1b4bc6f24465e"

[[kv_namespaces]]
binding = "USER_METADATA_KV"
id = "${USER_METADATA_KV_ID}"
preview_id = "${USER_METADATA_KV_PREVIEW_ID}"

[[kv_namespaces]]
binding = "CONTACT_REQUESTS_KV"
id = "${CONTACT_REQUESTS_KV_ID}"
preview_id = "${CONTACT_REQUESTS_KV_PREVIEW_ID}"
