name: Deploy Cloudflare Worker

on:
  push:
    branches: [ main ]

  jobs:
    publish:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - name: Install Wrangler
          run: npm install -g wrangler
        - name: Prepare wrangler.toml
          run: node scripts/prepare-wrangler.js
          env:
            USER_METADATA_KV_ID: ${{ secrets.USER_METADATA_KV_ID }}
            USER_METADATA_KV_PREVIEW_ID: ${{ secrets.USER_METADATA_KV_PREVIEW_ID }}
        - name: Validate configuration
          run: node scripts/validate-wrangler.js
          env:
            USER_METADATA_KV_ID: ${{ secrets.USER_METADATA_KV_ID }}
            USER_METADATA_KV_PREVIEW_ID: ${{ secrets.USER_METADATA_KV_PREVIEW_ID }}
            CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
        - name: Publish
          run: wrangler publish
          env:
            CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
