name: Deploy PHP Backend

on:
  push:
    paths:
      - '**/*.php'
      - 'questions.json'
      - '.github/workflows/deploy-backend.yml'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.BACKEND_SSH_KEY }}
      - name: Sync backend files
        run: |
          rsync -avz --delete \
            file_manager_api.php save-questions.php questions.json \
            ${{ secrets.BACKEND_USERNAME }}@${{ secrets.BACKEND_HOST }}:${{ secrets.BACKEND_PATH }}
