name: Deploy Cloudflare Worker

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ '*' ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Wrangler
        run: npm install -g wrangler

      - name: Check required secrets
        run: |
          missing=0
          for var in CLOUDFLARE_API_TOKEN USER_METADATA_KV_ID USER_METADATA_KV_PREVIEW_ID; do
            if [ -z "${!var}" ]; then
              echo "❌ Missing secret: $var"
              missing=1
            fi
          done
          if [ "$missing" -eq 1 ]; then
            echo "🚫 Deployment aborted due to missing secrets."
            exit 1
          fi
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          USER_METADATA_KV_ID: ${{ secrets.USER_METADATA_KV_ID }}
          USER_METADATA_KV_PREVIEW_ID: ${{ secrets.USER_METADATA_KV_PREVIEW_ID }}

      - name: Prepare wrangler.toml
        run: node scripts/prepare-wrangler.js
        env:
          USER_METADATA_KV_ID: ${{ secrets.USER_METADATA_KV_ID }}
          USER_METADATA_KV_PREVIEW_ID: ${{ secrets.USER_METADATA_KV_PREVIEW_ID }}

      - name: Update compatibility date
        run: node scripts/update-compat-date.js

      - name: Validate configuration
        run: node scripts/validate-wrangler.js
        env:
          USER_METADATA_KV_ID: ${{ secrets.USER_METADATA_KV_ID }}
          USER_METADATA_KV_PREVIEW_ID: ${{ secrets.USER_METADATA_KV_PREVIEW_ID }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}

      - name: Deploy to Cloudflare Workers
        run: wrangler deploy
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
