name: Deploy Cloudflare Worker

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ '*' ]
  workflow_dispatch:

jobs:
  deploy:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - name: Install Wrangler
          run: npm install -g wrangler
        - name: Prepare wrangler.toml
          run: node scripts/prepare-wrangler.js
          env:
            USER_METADATA_KV_ID: ${{ secrets.USER_METADATA_KV_ID }}
            USER_METADATA_KV_PREVIEW_ID: ${{ secrets.USER_METADATA_KV_PREVIEW_ID }}
        - name: Update compatibility date
          run: node scripts/update-compat-date.js
        fi
  env:
    CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
        - name: Validate configuration
          run: node scripts/validate-wrangler.js
          env:
            USER_METADATA_KV_ID: ${{ secrets.USER_METADATA_KV_ID }}
            USER_METADATA_KV_PREVIEW_ID: ${{ secrets.USER_METADATA_KV_PREVIEW_ID }}
            CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
        - name: Deploy
          run: wrangler deploy
          env:
            CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
